database:
  path: "database"
  table_name: "coco_82k"
  embedding_dim: 512

dataset:
  images_path: "./dataset/coco_random"
  batch_size: 64

model:
  name: "ViT-B-32"
  pretrained_model: "laion2b_s34b_b79k"
