database:
  path: "database/nature"
  table_name: "flora_20k_multi"
  embedding_dim: 512

dataset:
  images_path: "./dataset/flora_images"
  batch_size: 64

model:
  name: "ViT-B-32"
  pretrained_model: "laion2b_s34b_b79k"
